// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtHdab14MRAe-8Lk-iEprzjoIr32rziG0',
    appId: '1:471556535431:web:8054f4b2c4482f87557422',
    messagingSenderId: '471556535431',
    projectId: 'al-ridha-c6588',
    authDomain: 'al-ridha-c6588.firebaseapp.com',
    storageBucket: 'al-ridha-c6588.appspot.com',
    measurementId: 'G-C5KTGETBWV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABFUtG_6u8Mm18XOjrhhz32SnEu8KEKx8',
    appId: '1:471556535431:android:f3fec0cf85063006557422',
    messagingSenderId: '471556535431',
    projectId: 'al-ridha-c6588',
    storageBucket: 'al-ridha-c6588.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHoWipOD4rGemWEBvLQjqJtpQ-HsfdtG0',
    appId: '1:471556535431:ios:b6f3e53e7973df05557422',
    messagingSenderId: '471556535431',
    projectId: 'al-ridha-c6588',
    storageBucket: 'al-ridha-c6588.appspot.com',
    iosBundleId: 'com.example.alridafrieds',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHoWipOD4rGemWEBvLQjqJtpQ-HsfdtG0',
    appId: '1:471556535431:ios:5c9baea3255496bf557422',
    messagingSenderId: '471556535431',
    projectId: 'al-ridha-c6588',
    storageBucket: 'al-ridha-c6588.appspot.com',
    iosBundleId: 'com.example.alridafrieds.RunnerTests',
  );
}
